# Build stage
FROM maven:3.9.5-eclipse-temurin-17 AS build
WORKDIR /workspace

COPY pom.xml .
COPY src ./src

RUN mvn -B -DskipTests package

# Runtime stage
FROM eclipse-temurin:17-jre-jammy
WORKDIR /app

COPY --from=build /workspace/target/product-0.0.1-SNAPSHOT.jar ./product.jar

EXPOSE 8081
ENTRYPOINT ["java", "-jar", "/app/product.jar"]
